aoi:
  place_name: Manila, Philippines
  area_name: Manila
  abbr: mnl
  bbox:
    west: 120.942307
    south: 14.555838
    east: 121.029940
    north: 14.642303

elevation:
  out_dir: data/dem
  cache_dir: data/dem/raster
  tiles:
    - s3://copernicus-dem-30m/Copernicus_DSM_COG_10_N14_00_E120_00_DEM/Copernicus_DSM_COG_10_N14_00_E120_00_DEM.tif
    - s3://copernicus-dem-30m/Copernicus_DSM_COG_10_N14_00_E121_00_DEM/Copernicus_DSM_COG_10_N14_00_E121_00_DEM.tif

folium:
  starting_lat: 14.6462733
  starting_long: 121.0460557
  zoom_start: 12

mapillary_api:
  image_retrieval:
    out_dir: data/images/
    per_cell_limit: 2000
    cell_size_m: 500
    cell_overlap_m: 50
    fields: ["id", "captured_at", "camera_type", "compass_angle", "sequence", "thumb_1024_url",
            "thumb_2048_url", "computed_geometry", "width", "height"]
    fallback_fields: ["id", "captured_at", "camera_type", "compass_angle", "sequence", "thumb_1024_url",
            "thumb_2048_url", "geometry", "width", "height"]
  manifest:
    out_dir: data/meta/
    repo_manifest_name: mapillary_manifest.csv
    local_manifest_name: mapillary_manifest_local.csv
    repo_fields: ["id", "thumb_kind", "captured_at", "camera_type",
                  "sequence", "lat", "lon", "width", "height", "face", 
                  "yaw_deg", "pitch_deg", "hfov_deg"]